version: "3.8"
services:
  # Application
  app:
    build: "."
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-dbname}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  database_data: